pipeline {
    agent any
    stages {
        stage ('00 - Prepare jenkins.yaml') {
            when {
                changeset "**/jenkins.yaml"
            }
            steps {
                script {
                    // trigger build to revoke access token
                    build(
                        job: 'codeDeploy/prepareJcasc', 
                        propagate: true, 
                        wait: true,
                        parameters: [
                            stringParam(name: 'gitBranch', value: env.gitBranch)
                            stringParam(name: 'gitAccount', value: env.gitAccount),
                            stringParam(name: 'gitRepo', value: env.gitRepo),
                        ]
                    )
                }
            }
        }
        stage ('10 - Reload jenkins.yaml') {
            when {
                changeset "**/jenkins.yaml"
            }
            steps {
                script {
                    echo 'pending'
                    /*
                    // trigger build to revoke access token
                    build(
                        job: 'codeDeploy/reloadJcasc', 
                        propagate: true, 
                        wait: true
                    )
                    */
                }
            }
        }
    }
}