pipeline {
    agent any
    stages {
        stage ('00 - Prepare jenkins.yaml') {
            steps {
                sh(
                    script: """
                        cp $WORKSPACE/config/jenkins.yaml $JENKINS_HOME
                        sed -i 's/{gitAccount}/$gitAccount/g' $JENKINS_HOME/jenkins.yaml
                        sed -i 's/{gitRepo}/$gitRepo/g' $JENKINS_HOME/jenkins.yaml
                    """
                )
            }
        }
    }
}