pipeline {
    agent any
    stages {
        stage ('00 - Configure jenkins.yaml') {
            steps {
                sh(
                    script: """
                        cp $WORKSPACE/config/jenkins.yaml $JENKINS_HOME
                        sed -i 's/{serviceName}/$serviceName/g;' /var/lib/jenkins/jenkins.yaml,
                        sed -i 's/{domain}/$domainName/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{environment}/$environment/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{adminUsername}/$adminUsername}/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{adminEmail}/$adminEmail}/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{samlMetadataUrl}/$samlMetadataUrl/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{samlLogoutUrl}/$samlLogoutUrl}/g;' /var/lib/jenkins/jenkins.yaml",
                        sed -i 's/{gitAccount}/$gitAccount/g' $JENKINS_HOME/jenkins.yaml
                        sed -i 's/{gitRepo}/$gitRepo/g' $JENKINS_HOME/jenkins.yaml
                    """
                )
            }
        }
    }
}